### PR TITLE
replace carlys with carly silos....again. where do they come from? me.

### PR DESCRIPTION
**Pull request by ajkrumholz**
This is become a meme at this point.
Where do these carlys come from?

Like the NYC Subway always says:

If you see Carly, say Carly-Silos

### CODE REVIEW

**Comment by ajkrumholz** [comment]
Also can everyone make sure to pull this one down and fast forward to whatever you're working on? I don't mind squashing carly's up to a point but I'm having terrible flashbacks to my last project eval, when several of our passing tests all of a sudden failed in front of Chris. If this happens again I will never forgive myself, or Carly Simon.

**Comment by ajkrumholz** [comment]
Also can everyone make sure to pull this one down and fast forward to whatever you're working on? I don't mind squashing carly's up to a point but I'm having terrible flashbacks to my last project eval, when several of our passing tests all of a sudden failed in front of Chris. If this happens again I will never forgive myself, or Carly Simon.

**Review by Alaina-Noel — APPROVED** [review]
I changed them in mine, too. They are relentless.

**Comment by LlamaBack** [comment]
l o l. sorry for merging so late

**Review by LlamaBack — APPROVED** [review]

**Pull request merged**
