### PR TITLE
11 rails csv loadall

### LINKED ISSUE #11: rails csv_load:all

### PR DESCRIPTION
**Pull request by ajkrumholz**
Contains basic model and controller files
Contains rake tasks to read from csv files in db/data, can be executed sequentially using rails csv_load:all

### CODE REVIEW

**Comment by LlamaBack** [comment]
approved!

**Review by LlamaBack — APPROVED** [review]
awesome job with the rake tasks!

**Review by Alaina-Noel — APPROVED** [review]
This is great! We viewed this together over zoom.

**Review by Astrid-Hecht — APPROVED** [review]
everything looks good, I like your conversion of the status values into integers!

**Pull request merged**
